###create
POST http://localhost:3000/products/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjQ2NGI0NzI5OWMyMTRhZTIxNjk3YWU5IiwiaWF0IjoxNjk1MTE1MDk4fQ.HLDQTRh6wLPa5F5Uun7xRUNFiHt-1J1IH5XAC9nVgAk
Content-Type: application/json

{
    "name": "flaga545345435",
    "comment": "testowanie",
    "operations": [
        {   "name" : "druk",
            "type": "645ced6a19423e4e9b7b3dba",
            "stage_id": "1",
            "workSpace_type": "1",
            "nextOperation": null,
            "previousOperation":null
        },
        {   "name" : "wypalanie",
            "type": "645ced6119423e4e9b7b3db8",
            "stage_id": "2",
            "workSpace_type": "2",
            "nextOperation": null,
            "previousOperation":null
        }
    ]
}