###create
POST http://localhost:3000/orders/createneworder
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgZW51bSIsInN1YiI6IjY0NTM4YzAwMDY2YzZhMjg1ZTIxNzA2YSIsImlhdCI6MTY4MzE5NjkzN30.8QS4m9NjbCLIJaEp6k5yUH8TvTFx-Yj1EDmv9iRfMTA
Content-Type: application/json

{
    "name": "zamowienie 2 simple",
    "orderNo": "fsdfds-2023",
    "products_types": [
        {"qty": 25, "product_type":"645cee0cbd7a2c0a06de9887"},
        {"qty": 35, "product_type":"645cee2ebd7a2c0a06de9889"}
        ],
    "products":[]
    
}

### start
GET http://localhost:3000/orders/start/645ceea3cca3aafc9877dcd6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgZW51bSIsInN1YiI6IjY0NTM4YzAwMDY2YzZhMjg1ZTIxNzA2YSIsImlhdCI6MTY4MzE5NjkzN30.8QS4m9NjbCLIJaEp6k5yUH8TvTFx-Yj1EDmv9iRfMTA 


###add product
POST http://localhost:3000/orders/addProduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgZW51bSIsInN1YiI6IjY0NTM4YzAwMDY2YzZhMjg1ZTIxNzA2YSIsImlhdCI6MTY4MzE5NjkzN30.8QS4m9NjbCLIJaEp6k5yUH8TvTFx-Yj1EDmv9iRfMTA
Content-Type: application/json

{
    "order_id": "645cef1dcca3aafc9877dcdd",
    "qty": 55,
    "productType_id": "645cee2ebd7a2c0a06de9889"
    
}


